name: Publish Docker Image

on:
  push:
    branches:
      - main  # Ejecutar cuando se hace push en la rama 'main'
  workflow_dispatch:  # Permitir ejecución manual del flujo de trabajo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
